services:
  redis:
    image: redis:latest
    container_name: redis
    ports:
      - '6379:6379'
    volumes:
      - redis-data:/data

  postgres:
    image: postgres:latest
    container_name: postgres
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
      POSTGRES_DB: netpulsedb
    ports:
      - '5432:5432'
    volumes:
      - postgres-data:/var/lib/postgresql/data

  netpulse:
    build: .
    container_name: netpulse-0.0.11
    ports:
      - '8080:8080'
    depends_on:
      - redis
      - postgres
    volumes:
      - ./.env:/root/.env

volumes:
  redis-data:
  postgres-data:
